GET http://localhost:8080/user/login?username=阿吉&password=123

###
GET http://localhost:8080/user/info

###
GET http://localhost:8080/user/token/login?username=阿彩&password=2333

###
GET http://localhost:8080/user/token/info?token=

### JWT
GET http://localhost:8080/user/jwt/login?username=燕十三&password=666

###
GET http://localhost:8080/user/jwt/info?token=

###